
train_cupid = """
CREATE TABLE data_train(
    age INT, 
    height FLOAT, 
    virgo INT, 
    taurus INT, 
    scorpio INT, 
    pisces INT, 
    libra INT, 
    leo INT,
    gemini INT, 
    aries INT, 
    aquarius INT, 
    cancer INT, 
    sagittarius INT,
    asian INT,
    "hispanic / latin" INT,
    black INT, 
    indian INT, 
    "pacific islander" INT,
    "native american" INT, 
    "middle eastern" INT, 
    colorado INT, 
    "new york" INT, 
    oregon INT,
    arizona INT, 
    hawaii INT, 
    montana INT, 
    wisconsin INT, 
    virginia INT, 
    spain INT,
    nevada INT, 
    illinois INT, 
    vietnam INT, 
    ireland INT, 
    louisiana INT, 
    michigan INT,
    texas INT, 
    "united kingdom" INT, 
    massachusetts INT, 
    "north carolina" INT, 
    idaho INT,
    mississippi INT, 
    "new jersey" INT, 
    florida INT, 
    minnesota INT, 
    georgia INT, 
    utah INT,
    washington INT, 
    "west virginia" INT, 
    connecticut INT, 
    tennessee INT,
    "rhode island" INT, 
    "district of columbia" INT, 
    canada INT, 
    missouri INT, 
    germany INT,
    pennsylvania INT, 
    netherlands INT, 
    switzerland INT, 
    mexico INT, 
    ohio INT,
    agnosticism INT, 
    atheism INT, 
    catholicism INT, 
    buddhism INT, 
    judaism INT,
    hinduism INT, 
    islam INT, 
    pro_dogs FLOAT, 
    pro_cats FLOAT, 
    spanish INT, 
    chinese INT,
    french INT, 
    german INT, 
    single INT, 
    seeing_someone INT, 
    available INT, 
    employed INT,
    income_between_25_50 INT, 
    income_between_50_75 INT, 
    income_over_75 INT,
    drugs_often INT, 
    drugs_sometimes INT, 
    "drinks_not at all" INT, 
    drinks_often INT,
    drinks_rarely INT, 
    drinks_socially INT, 
    "drinks_very often" INT,
    orientation_gay INT, 
    orientation_straight INT, 
    sex_m INT, 
    smokes_sometimes INT,
    "smokes_trying to quit" INT, 
    "smokes_when drinking" INT, 
    smokes_yes INT,
    body_type_overweight INT, 
    body_type_regular INT, 
    education_high_school INT,
    education_undergrad_university INT);
"""

test_cupid = """
CREATE TABLE data_test(
    age INT, 
    height FLOAT, 
    virgo INT, 
    taurus INT, 
    scorpio INT, 
    pisces INT, 
    libra INT, 
    leo INT,
    gemini INT, 
    aries INT, 
    aquarius INT, 
    cancer INT, 
    sagittarius INT,
    asian INT,
    "hispanic / latin" INT,
    black INT, 
    indian INT, 
    "pacific islander" INT,
    "native american" INT, 
    "middle eastern" INT, 
    colorado INT, 
    "new york" INT, 
    oregon INT,
    arizona INT, 
    hawaii INT, 
    montana INT, 
    wisconsin INT, 
    virginia INT, 
    spain INT,
    nevada INT, 
    illinois INT, 
    vietnam INT, 
    ireland INT, 
    louisiana INT, 
    michigan INT,
    texas INT, 
    "united kingdom" INT, 
    massachusetts INT, 
    "north carolina" INT, 
    idaho INT,
    mississippi INT, 
    "new jersey" INT, 
    florida INT, 
    minnesota INT, 
    georgia INT, 
    utah INT,
    washington INT, 
    "west virginia" INT, 
    connecticut INT, 
    tennessee INT,
    "rhode island" INT, 
    "district of columbia" INT, 
    canada INT, 
    missouri INT, 
    germany INT,
    pennsylvania INT, 
    netherlands INT, 
    switzerland INT, 
    mexico INT, 
    ohio INT,
    agnosticism INT, 
    atheism INT, 
    catholicism INT, 
    buddhism INT, 
    judaism INT,
    hinduism INT, 
    islam INT, 
    pro_dogs FLOAT, 
    pro_cats FLOAT, 
    spanish INT, 
    chinese INT,
    french INT, 
    german INT, 
    single INT, 
    seeing_someone INT, 
    available INT, 
    employed INT,
    income_between_25_50 INT, 
    income_between_50_75 INT, 
    income_over_75 INT,
    drugs_often INT, 
    drugs_sometimes INT, 
    "drinks_not at all" INT, 
    drinks_often INT,
    drinks_rarely INT, 
    drinks_socially INT, 
    "drinks_very often" INT,
    orientation_gay INT, 
    orientation_straight INT, 
    sex_m INT, 
    smokes_sometimes INT,
    "smokes_trying to quit" INT, 
    "smokes_when drinking" INT, 
    smokes_yes INT,
    body_type_overweight INT, 
    body_type_regular INT, 
    education_high_school INT,
    education_undergrad_university INT);
"""